# -*- coding: UTF-8 -*-
import os
from pathlib import Path


__all__ = ["LLMBackend"]

_MODEL_CACHE_DIR = Path(os.path.expanduser("~/.cache/pboxllm/models"))


class LLMBackend:
    """Wrapper around llama-cpp-python providing model download-on-first-use and text generation.

    The model file is stored in ``~/.cache/pboxllm/models/`` so it persists across Docker container
    restarts when the home directory is bind-mounted as a volume.

    Parameters
    ----------
    model_file : str
        Filename of the GGUF model (e.g. ``mistral-7b-instruct-v0.2.Q4_K_M.gguf``).

    model_repo : str
        HuggingFace repository id from which the model is downloaded if not already cached
        (e.g. ``TheBloke/Mistral-7B-Instruct-v0.2-GGUF``).

    n_ctx : int, default=2048
        Token context window size.

    n_threads : int, default=4
        Number of CPU threads used for inference.

    Attributes
    ----------
    model_path_ : Path
        Resolved path to the local GGUF model file.
    """

    def __init__(self, model_file, model_repo, n_ctx=2048, n_threads=4):
        self.model_file = model_file
        self.model_repo = model_repo
        self.n_ctx = n_ctx
        self.n_threads = n_threads
        self._llm = None

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def load(self):
        """Ensure the model is downloaded and loaded into memory.

        Safe to call multiple times, loads only on first call.
        """
        if self._llm is not None:
            return
        self.model_path_ = self._ensure_model()
        from llama_cpp import Llama
        self._llm = Llama(model_path=str(self.model_path_), n_ctx=self.n_ctx, n_threads=self.n_threads, verbose=False)

    def generate(self, prompt, max_tokens=64, temperature=0.0):
        """Run inference and return the raw generated text.

        Parameters
        ----------
        prompt : str
            The full prompt string to send to the model.

        max_tokens : int, default=64
            Maximum number of tokens to generate.

        temperature : float, default=0.0
            Sampling temperature. 0.0 means greedy (deterministic).

        Returns
        -------
        str
            Raw text generated by the model.
        """
        if self._llm is None:
            self.load()
        result = self._llm(prompt, max_tokens=max_tokens, temperature=temperature, echo=False)
        return result["choices"][0]["text"].strip()

    # ------------------------------------------------------------------
    # Model management
    # ------------------------------------------------------------------

    def _ensure_model(self):
        """Return the path to the local model file, downloading it first if needed."""
        _MODEL_CACHE_DIR.mkdir(parents=True, exist_ok=True)
        dest = _MODEL_CACHE_DIR / self.model_file
        if dest.exists():
            return dest
        print(f"[pboxllm] Model '{self.model_file}' not found in cache. Downloading from '{self.model_repo}'...")
        try:
            from huggingface_hub import hf_hub_download
            downloaded = hf_hub_download(repo_id=self.model_repo, filename=self.model_file, local_dir=str(_MODEL_CACHE_DIR))
            return Path(downloaded)
        except Exception as exc:
            raise RuntimeError(
                f"[pboxllm] Failed to download model '{self.model_file}' from '{self.model_repo}': {exc}\n"
                f"You can also place the GGUF file manually at: {dest}"
            ) from exc
