#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *


def parse(output):
    for l in output.splitlines():
        try:
            return re.search(r"^[^:]+:\s+packer:\s+([^([{]+)", l).group(1).lower()
        except AttributeError:
            pass


if __name__ == "__main__":
    run("DIE", parse_func=parse)

