#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import json, run


def parse(output):
    packer_strings = json.loads(output).get('peinfo', {}).get('features', {}).get('packer', [])
    # filter some patterns found by trial and error
    for s in packer_strings[:]:
        if s.startswith("Microsoft_Visual_Cpp_"):
            packer_strings.remove(s)
    return packer_strings or [None]


if __name__ == "__main__":
    run("PeFrame", parse_func=parse, exe_type="pe", exe_help="path to the PE file")

