#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *


def parse(output):
    return json.loads(output).get('peinfo', {}).get('features', {}).get('packer', [])


if __name__ == "__main__":
    run("PeFrame", parse_func=parse, exe_type="pe", exe_help="path to the PE file")

