#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import run
from pypackerdetect import PyPackerDetect
from sys import stderr


def execute(name, **kwargs):
    try:
        return PyPackerDetect(logger=kwargs['logger']).detect(kwargs['path'])['detections'], None
    except Exception as e:
        return None, str(e)


if __name__ == "__main__":
    run("PyPackerDetect", exec_func=execute, exe_type="pe", exe_help="path to the PE file")

