#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pbox import *
from tinyscript import *


__script__       = "Alteration manipulation tool"
__version__      = "1.0.0"
__doc__         = """
This tool aims to manipulate a alteration set in many ways including its creation, update, selection, merging or export.
"""
__description__ = "Manipulate alteration sets for use with Adversarial Learning"
__examples__    = [
    "show custom-alterations.yml",
]


conf_does_not_exist = lambda a: ts.file_does_not_exist(Locator(f"conf://{a}", new=True))
conf_does_not_exist.__name__ = "non-existing configuration file"


if __name__ == '__main__':
    sparsers = parser.add_subparsers(dest="command", metavar="CMD", title="positional argument",
                                 help="command to be executed")
    add_argument(sparsers.add_parser("browse", help="browse alterations set's metadata"), "exeformat",
                 "alterations-set")
    # compute
    export = sparsers.add_parser("export", help="export alteration definitions to a given format")
    add_argument(export, "expformat", "alterations-set")
    insp = sparsers.add_parser("inspect", help="inspect the selected alterations of a target set")
    add_argument(insp, "exeformat", "alterations-set", "query")
    # merge
    # plot
    # remove
    select = sparsers.add_parser("select", help="select alterations from a target set")
    select.add_argument("destination", type=conf_does_not_exist,
                        help="destination YAML file with the selected alterations")
    add_argument(select, "exeformat", "alterations-set", "query")
    add_argument(sparsers.add_parser("show", help="show statistics about the target set"), "alterations-set")
    # update
    initialize(noargs_action="usage")
    configure_logging(args.verbose)
    set_yaml(args)
    # compute alterations registry
    Alterations()
    # now execute
    Alterations.source = args.config_file = args.alterations_set
    getattr(Alterations, args.command)(**vars(args))

