#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pbox import *
from tinyscript import *


__script__       = "Feature manipulation tool"
__version__      = "1.0.1"
__contributors__ = [
    {'author': "Alex Van Mechelen", 'reason': "largely contributed to advanced feature engineering and proposed the "
                                              "creation of this tool"},
]
__doc__         = """
This tool aims to manipulate a feature set in many ways including its creation, update, selection, merging or export.
"""
__description__ = "Manipulate feature sets for use with Machine Learning"
__examples__    = [
    "compute test.exe",
    "export --features-set my-cumstom-features.yml --format ELF --output csv",
    "select --format PE -q 'significant == \"True\"' --output significant-features.yml",
    "select --features-set my-cumstom-features.yml --query 'tags == \"some-tag\"'",
    "show custom-features.yml",
]


conf_does_not_exist = lambda f: ts.file_does_not_exist(Locator(f"conf://{f}", new=True))
conf_does_not_exist.__name__ = "non-existing configuration file"


if __name__ == '__main__':
    sparsers = parser.add_subparsers(dest="command", metavar="CMD", title="positional argument",
                                     help="command to be executed")
    add_argument(sparsers.add_parser("compute", help="compute target executable's features"),
                 "executable", "features-set", single=True)
    export = sparsers.add_parser("export", help="export feature definitions to a given format")
    add_argument(export, "expformat", "exeformat", "features-set", "query")
    add_argument(sparsers.add_parser("list", help="list feature names"), "features-set")
    # plot
    # remove
    select = sparsers.add_parser("select", help="select features from a target set")
    add_argument(select, "exeformat", "features-set")
    select.add_argument("-o", "--output", type=conf_does_not_exist, help="output YAML file with the selected features")
    add_argument(select, "query")
    select.add_argument("-s", "--split-on", choices=["category", "ptime", "tcomplexity"],
                        help="split the selected features according to the specified attribute",
                        note="if --output is not defined, it sets it to 'features.yml' by default")
    add_argument(sparsers.add_parser("show", help="show statistics about the target features set"), "features-set")
    # update
    initialize(noargs_action="usage")
    configure_logging(args.verbose)
    set_yaml(args)
    Features.config = args.config_file = args.features_set
    Features()
    if args.command == "compute":
        Executable(args.executable, logger=logger).show(False, False, True)
    elif args.command == "list":
        for fn in Features.names:
            print(fn)
    else:
        getattr(Features, args.command)(**vars(args))

