#!/usr/bin/python3
# PYTHON_ARGCOMPLETE_OK
# -*- coding: UTF-8 -*-
from pbox import *
from pbox.__info__ import *
from pbox.common.rendering import *
from tinyscript import *
from tinyscript.report import *


__script__      = "packing-box"
__version__     = "1.2.0"
__description__ = "Display this help message or packer's help"


BANNER_ARG   = "item"
BANNER_FONT  = "starwars"
BANNER_STYLE = {'fgcolor': "lolcat"}
TEMPLATE  = """
This Docker image is a ready-to-use platform for making datasets of packed and not packed executables, especially for training machine learning models.
"""


def overview(show=False, format=None, category=None, keep=None):
    """ Display an overview of tools, detectors, packers, unpackers and datasets. """
    report, n = [Text(TEMPLATE)], 0
    if keep is None:
        tools = []
        tools_headers = ["Name", "Description", "Version"]
        for tool in ts.Path(__file__).dirname.listdir(lambda f: f.is_file()):
            row = [tool.stem, "", ""]
            try:
                for line in tool.read_text().splitlines():
                    if re.match(r"__(description|version)__", line):
                        row[[1, 2]["__version__" in line]] = line.split("=", 1)[-1].strip(" \"")
            except UnicodeDecodeError:
                continue
            if row[1]:
                tools.append(row)
        report.append(Section("Tools (%d)" % len(tools)))
        report.append(Table(tools, column_headers=tools_headers))
    descr = {}
    for cls in ([Analyzer, Detector, Packer, Unpacker] if keep is None else [globals()[keep[:-1].capitalize()]]):
        r, d = cls.summary(show, format, **({'categories': category} if cls is Packer else {}))
        if cls is Detector:
            table, cols = r[1], ["Multiclass", "Weak Mode", "Superdetector"]
            for col in cols:
                table.column_headers.insert(-1, col)
            data = []
            for row in table.data:
                dcls = Detector.get(row[0])
                bad, good = (NOK, OK) if dcls.status == "ok" else (NOK_GREY, OK_GREY)
                for col, default in [("multiclass", True), ("weak", False), ("vote", True)]:
                    row.insert(-1, [bad, good][getattr(dcls, col, default)])
                data.append(row)
            table.data = data
        for _ in r:
            report.append(_)
        descr.update(d)
    report.append(Section("Legend"))
    report.append(Text(" ; ".join("%s  %s" % (k, v) for k, v in sorted(descr.items(), key=lambda x: x[1]))))
    if keep is None:
        for s in Dataset.summarize(".", args.show_all):
            report.append(s)
    return report


if __name__ == '__main__':
    valid_categories = tuple(sorted(set(c for p in Packer.registry for c in getattr(p, "categories", [])))) + ("All", )
    megs = [parser.add_mutually_exclusive_group() for i in range(4)]
    megs[0].add_argument("-c", "--category", choices=valid_categories, help="filter on a category of packers")
    megs[1].add_argument("-f", "--format", default="All", help="filter on a format of executables")
    for i in range(4):
        megs[i].add_argument("-i", "--item", help="get help for a particular detector, packer or unpacker")
    megs[2].add_argument("-k", "--keep", choices=["detectors", "packers", "unpackers"],
                         help="only keep detectors, packers or unpackers")
    megs[3].add_argument("-s", "--show-all", action="store_true", help="show all packers, even those that are broken")
    initialize(autocomplete=True)
    logger.name = "help"
    logging.configLogger(logger, ["INFO", "DEBUG"][args.verbose], fmt=LOG_FORMATS[args.verbose], relative=True)
    if args.item is None:
        render(*overview(args.show_all, args.format, args.category, args.keep))
    else:
        subcls = None
        for cls in [Detector, Packer, Unpacker]:
            subcls = cls.get(args.item, error=False)
            if subcls:
                render(subcls.help())
                break
        if subcls is None:
            logger.error("%s not found" % args.item)

