#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pbox import *
from tinyscript import *


__script__      = "Unpacking tool"
__version__     = "1.0.2"
__doc__         = """
This tool simply unpacks (using Unpacker.unpack) with the selected unpacker an executable or folder of executables.
"""
__description__ = "Unpack an input executable/folder with the selected unpacker"
__examples__    = [
    "upx /tmp/cscript.exe",
    "unipacker samples/",
    "retdec-unpacker dataset-test-upx",
]


if __name__ == '__main__':
    parser.add_argument("unpacker", type=Unpacker.get, help="selected unpacker")
    parser.add_argument("executable", help="executable or folder containing executables")
    initialize(noargs_action="usage", multi_level_debug=True, autocomplete=True)
    logging.configLogger(logger, ["INFO", "DEBUG"][args.verbose], fmt=LOG_FORMATS[args.verbose], relative=True)
    p = ts.Path(args.executable)
    delattr(args, "executable")
    if p.is_file():
        args.unpacker.unpack(p.absolute(), **vars(args))
    elif p.is_dir():
        with progress_bar(transient=True) as pb:
            for f in pb.track(p.listdir(is_exe)):
                args.unpacker.unpack(f.absolute(), **vars(args))

