#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from tinyscript import *


__version__     = "1.0.0"
__doc__         = """
This is a dummy wrapper for bytehist for using it in no-GUI mode only.
"""
__examples__    = [
    "program.exe",
    "program.exe --output hist.png",
    "program.exe -o hist.jpg",
    "program.exe -o hist.bmp",
]
__description__ = "Generate a bytes histogram of the input binary"


def valid_image(filename):
    ts.file_does_not_exist(filename)
    p = ts.Path(filename)
    if p.extension not in [".bmp", ".jpg", ".png"]:
        raise ValueError("Bad image extension (only supports BMP|JPG|PNG)")
    return p


if __name__ == "__main__":
    parser.add_argument("input", type=ts.file_exists, default="program.exe", help="binary to be represented")
    parser.add_argument("-o", "--output", type=valid_image, default="output.png",
                        help="destination image (BMP, JPG or PNG)")
    initialize()
    logger.info("Making bytes histogram of %s to %s..." % (args.input, args.output))
    ts.execute_and_log("xvfb-run ~/.opt/utils/bytehist_orig -n -s %s %s" % (args.output, args.input))

