#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pbox import *
from pbox.__info__ import *
from tinyscript import *


__version__     = "1.0.0"
__doc__         = """
This tool aims to detect the packer used on an input executable, folder of executables or Dataset.
"""
__examples__    = []
__description__ = "Detect the packer used on an input executable/folder/dataset"


if __name__ == '__main__':
    parser.add_argument("executable", help="executable or folder containing executables or dataset")
    parser.add_argument("-d", "--detector", action="extend", nargs="*", type=lambda d: Detector.get(d),
                        help="detector(s) to be used")
    initialize()
    if args.detector:
        for name in args.detector:
            r = Detector.get(name).detect(args.executable)
            if r:
                print(r)
    else:
        if args.verbose:
            r, details = Detector.detect(args.executable, debug=args.verbose)
        else:
            r, details = Detector.detect(args.executable), {}
        mlen = 0
        for name in details.keys():
            mlen = max(mlen, len(name))
        for name, label in details.items():
            logger.debug(("{: <%d}: {}" % mlen).format(name, "unknown" if label is None else label))
        if r:
            print(r)

