#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pbox import *
from pbox.__info__ import *
from tinyscript import *


__version__     = "1.0.1"
__doc__         = """
This tool aims to detect the packer used on an input executable, folder of executables or Dataset.
"""
__examples__    = []
__description__ = "Detect the packer used on an input executable/folder/dataset"


if __name__ == '__main__':
    parser.add_argument("executable", help="executable or folder containing executables or dataset")
    parser.add_argument("-d", "--detector", action="extend", nargs="*", type=lambda d: Detector.get(d),
                        help="detector(s) to be used")
    initialize(noargs_action="help", multi_level_debug=True)
    kw = {'debug': args.verbose > 0, 'verbose': args.verbose > 1}
    if args.detector:
        for name in args.detector:
            for e, r in Detector.get(name).detect(args.executable, **kw):
                print(e, r)
    else:
        for r in Detector.detect(args.executable, **kw):
            try:
                e, r, details = r
            except:
                e, r = r
                details = {}
            mlen = 0
            for name in details.keys():
                mlen = max(mlen, len(name))
            for name, label in details.items():
                logger.warning(("{: <%d}: {}" % mlen).format(name, label or "-"))
            print(e, r)

