#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pbox import *
from tinyscript import *


__author__      = "Alexandre D'Hondt"
__email__       = "alexandre.dhondt@gmail.com"
__version__     = "1.1.2"
__copyright__   = ("A. D'Hondt", 2021)
__license__     = "gpl-3.0"
__doc__         = """
This utility aims to facilitate packers' install according to the YAML packers data file.
"""
__description__ = "Installing packers (based on /opt/packers/packers.yml)"


if __name__ == '__main__':
    parser.add_argument("packer", default=[], action="extend", nargs="*", help="specific packer to install")
    initialize()
    for packer in PACKERS:
        name = packer.__class__.__name__
        if not args.packer or packer.name in list(map(lambda x: x.lower(), args.packer)):
            try:
                packer.setup()
            except:
                logger.critical("Packer install failed: %s" % name)
                raise

