#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pbox import *
from tinyscript import *


__author__      = "Alexandre D'Hondt"
__email__       = "alexandre.dhondt@gmail.com"
__version__     = "1.1.0"
__copyright__   = ("A. D'Hondt", 2021)
__license__     = "gpl-3.0"
__doc__         = """
This utility aims to facilitate packers' install according to the YAML packers data file.
"""
__description__ = "A tool for easily installing packers based on a YML config file."


if __name__ == '__main__':
    parser.add_argument("-c", "--config", type=ts.yaml_config, default="packers.yml",
                        help="YAML configuration file for installing packers")
    parser.add_argument("-p", "--packer", nargs="*", help="specific packer to install")
    initialize()
    for packer in PACKERS:
        if args.packer and all(packer.name not in list(map(lambda x: x.lower(), args.packer or []))):
            logger.debug("Skipping %s..." % packer)
            continue
        try:
            packer.setup()
        except:
            logger.critical("Packer install failed: %s" % packer)
            raise

