#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from bintropy import bintropy
from bintropy.__info__ import __author__, __license__, __source__, __version__
from pboxtools import *


@version("Bintropy %s <%s> by %s\nLicensed under %s" % (__version__, __source__, __author__, __license__))
@catch_exception
def execute(name, **kwargs):
    return str(bintropy(kwargs['path'], logger=kwargs['logger']))


if __name__ == "__main__":
    run("Bintropy", exec_func=execute, binary_only=True)

