#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from bintropy import bintropy
from bintropy.__info__ import __author__, __license__, __source__, __version__
from pboxtools import run, version, DETECTORS


@version("Bintropy %s <%s> by %s\nLicense %s" % (__version__, __source__, __author__, __license__))
def execute(name, **kwargs):
    try:
        return str(bintropy(kwargs['path'], logger=kwargs['logger'])), None
    except Exception as e:
        return None, str(e)


if __name__ == "__main__":
    run("Bintropy", exec_func=execute, binary_only=True)

