#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *


def parse(output, **kwargs):
    r = []
    for l in output.splitlines():
        with suppress(AttributeError):
            r.append(re.search(r"^[^:]+:\s+(?:packer|protector):\s+(.+)", l).group(1))
    return r


if __name__ == "__main__":
    run("DIE", parse_func=parse)

