#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import re, run


def parse(output, **kwargs):
    r = []
    for l in output.splitlines():
        try:
            r.append(re.search(r"^[^:]+:\s+(?:packer|protector):\s+(.+)", l).group(1).lower() \
                     .replace("'s", "").replace(" ", "_").replace("(", "").replace(")", ""))
        except AttributeError:
            pass
    return r


if __name__ == "__main__":
    run("DIE", parse_func=parse)

