#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *


def parse(output, **kwargs):
    r = []
    for l in output.splitlines():
        l = l.strip()
        if l == "Found no known modifier or compiler.":
            return []
        with suppress(AttributeError):
            r.append(re.search(r"^Packer:\s+(.+)$", l).group(1))
            continue
        if kwargs['weak']:
            with suppress(AttributeError):
                r.append(re.search(r"^Probably compressed(.*)$", l).group(1))
    return r


if __name__ == "__main__":
    run("GetTyp", parse_func=parse, exe_type="pe", exe_help="path to the PE file", weak_assumptions=True)

