#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import json, run


def parse(output):
    js = json.loads(output)
    packer_strings = js.get('peinfo', {}).get('features', {}).get('packer', [])
    if any(d.get('packer_compiler_signatures.yar', "") == "IsPacked" for d in js.get('yara_plugins', [])):
        packer_strings.append("unknown")
    for s in js.get('strings', {}).get('dump', []):
        if "packed" in s.lower():
            packer_strings.append(s)
    # filter some patterns found by trial and error
    for s in packer_strings[:]:
        if s.startswith("Microsoft_Visual_Cpp_"):
            packer_strings.remove(s)
    return packer_strings or [None]


if __name__ == "__main__":
    run("PeFrame", parse_func=parse, exe_type="pe", exe_help="path to the PE file")

