#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *
from peid import identify_packer
from peid.__info__ import __author__, __license__, __source__, __version__


ARGS = [
    [("-d", "--db"), {'help': "signatures database"}],
]


@version("Packed Executable iDentifier (Python version) %s <%s> by %s\nLicensed under %s" % \
         (__version__, __source__, __author__, __license__))
@catch_exception
def execute(name, **kwargs):
    return identify_packer(kwargs['path'], db=kwargs['orig_args']['db'], logger=kwargs['logger'])[0][1]


def parse(output, **kwargs):
    return list(map(lambda x: x.split("->")[0].strip(), output))


if __name__ == "__main__":
    run("PEiD", exec_func=execute, parse_func=parse, exe_type="pe", exe_help="path to the PE file", parser_args=ARGS)

