#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *


ARGS = [
    [("-d", "--db"), {'default': "/opt/detectors/userdb.txt", 'help': "signatures database"}],
]


def parse(output, **kwargs):
    for l in output.splitlines():
        if "no packer found" in l:
            return
        # important note: this tool uses the same signature DB format as PEiD, it is therefore expected to produce the
        #                  same kind of output
        with suppress(AttributeError):
            p = re.search(r"^packer:\s+(.*)$", l).group(1).lower()
            p = re.search(r"^(?:.*?)((?:[a-z$][a-z0-9]{2,}(?:\d+)?(?:'s)?(?:\s+)?)+)", p).group(1).strip()
            p = p.replace("'s", "")
            p = re.sub(r"['/]", "", p)
            p = re.sub(r"[\s-]+", "_", p)
            return p.lower()


if __name__ == "__main__":
    run("PePack", parse_func=parse, exe_type="pe", exe_help="path to the PE file", parser_args=ARGS)

