#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import re, run


def parse(output, **kwargs):
    r = []
    for l in output.splitlines():
        with suppress(AttributeError):
            r.append(re.search(r"^\* Section name .+ is typical for (.+) packer$", l).group(1).lower())
        if kwargs['weak']:
            for p in [r"^Entry Point is in section \d+ with name (.+)$",
                      r"^\* Section \d+ with name (.+) has write and execute characteristics\.$",
                      r"^\* Entry point is in writeable section \d+ with name (.+)$",
                      r"^\* Section name is unusual: (.+)$"]:
                with suppress(AttributeError):
                    r.append(re.search(p, l).group(1).lower())
    return r


if __name__ == "__main__":
    run("PortEx", parse_func=parse, exe_type="pe", exe_help="path to the PE file", weak_assumptions=True)

