#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *
from pypackerdetect import PyPackerDetect
from pypackerdetect.__info__ import __author__, __credits__, __license__, __source__, __version__


@version("PyPackerDetect %s <%s> originally by %s, refactored by %s\nLicensed under %s" % \
         (__version__, __source__, __author__, __credits__, __license__))
@catch_exception
def execute(name, **kwargs):
    return PyPackerDetect(logger=kwargs['logger']).detect(kwargs['path'])


def parse(output, **kwargs):
    return output['detections'] + [[], output['suspicions']][kwargs['weak']]


if __name__ == "__main__":
    run("PyPackerDetect", exec_func=execute, parse_func=parse, exe_type="pe", exe_help="path to the PE file",
        weak_assumptions=True)

