#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *
from pypeid import PEiDScanner


@catch_exception
def execute(name, **kwargs):
    r = PEiDScanner(kwargs['logger']).scan_file(kwargs['path'])
    kwargs['logger'].debug("\n" + pformat(r, indent=4))
    return r['PEiD'] + [[], ["unknown"]][r['Packed'] == "yes"]


if __name__ == "__main__":
    run("PyPeid", exec_func=execute, exe_type="pe", exe_help="path to the PE file")

