#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import pformat, run
from pypeid import __version__, PEiDScanner


def execute(name, **kwargs):
    try:
        r = PEiDScanner().scan_file(kwargs['path'])
        kwargs['logger'].debug("\n" + pformat(r, indent=4))
        return r['PEiD'] or "", None
    except Exception as e:
        return None, str(e)


if __name__ == "__main__":
    run("PyPeid", exec_func=execute, exe_type="pe", exe_help="path to the PE file")

