#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *


def parse(output, **kwargs):
    r = []
    for l in output.splitlines():
        if l.strip() == "Warning: Unknown compiler or packer.":
            r.append("unknown")
            continue
        with suppress(AttributeError):
            r.append(re.sub(r"('s|[()])", "",
                            re.search(r"^Detected tool\s+:\s+(.+)\s+\((?:packer|protector|compressor)\)", l).group(1)))
    return r


if __name__ == "__main__":
    run("RetDec", parse_func=parse, parse_stderr=True)

