#!/usr/bin/python3
# -*- coding: UTF-8 -*-
from pboxtools import *


def parse(output, **kwargs):
    r, f = [], lambda s: re.sub(r"('s|[()])", "", s).replace(" ", "_")
    for l in output.splitlines():
        with suppress(AttributeError):
            r.append(f(re.search(r"^Detected tool\s+:\s+(.+)\s+\(packer\)(?:.+)$", l).group(1).lower()))
    return r


if __name__ == "__main__":
    run("RetDec", parse_func=parse)

