#!/bin/bash

# Custom system update function
system-update() {
  sudo apt-get update
  sudo apt-get upgrade -y
  sudo apt-get autoremove -y
  sudo apt-get autoclean
}

# pip-update
pip-upgrade() {
  sudo pip3 freeze - local \
    | grep -v "^\-e" \
    | cut -d = -f 1 \
    | xargs -n1 pip3 install --user --break-system-packages
}

# packing-box update command (development)
pbox-update() {
  if [ "$*" = "-h" ] || [ "$*" = "--help" ]; then
    echo "Usage: pbox-update [-n/--no-internet]"
  else
    printf "${CYA}Copying files from packing-box...${RST}\n"
    local OPT=$HOME/.opt
    cp -f /mnt/share/src/files/tools/* $OPT/tools/
    mv -f $OPT/tools/help $OPT/tools/?
    cp -f /mnt/share/src/conf/*.yml $OPT/
    for F in /mnt/share/src/term/*; do
      cp -f "$F" "$HOME/.${F##*/}"
    done
    source $HOME/.bashrc
    find /mnt/share/src/files/detectors/ -type f \( ! -iname \"*\.*\" \) -exec cp -f {} $OPT/bin/ \;
    mv -f $OPT/bin/userdb*.txt $OPT/detectors/
    wget -q --spider -T 1 http://www.google.com
    local ret=$?
    if [ ! "$*" = "-n" ] && [ ! "$*" = "--no-internet" ] && [ $ret -eq 0 ]; then
      printf "${CYA}Upgrading Pip...${RST}\n"
      pip3 -qq install --user --no-warn-script-location --break-system-packages --upgrade pip
      printf "${CYA}Upgrading pbox library...${RST}\n"
      pip3 -qq install --user --no-warn-script-location --break-system-packages --upgrade /mnt/share/src/lib/
    else
      printf "${CYA}Upgrading pbox library (ignore package index)...${RST}\n"
      pip3 -qq install --user --no-warn-script-location --break-system-packages --no-index --no-build-isolation --upgrade /mnt/share/src/lib/
    fi
  fi
}
