#!/bin/bash
function set_colors {
# Colors Definition
RST='\033[0m'   # Text Reset
# Regular               Bold                    Underline               Blink                   High Intensity          BoldHigh Intens         Background              High Intensity Backgrounds
BLA='\033[0;30m';       BBLA='\033[1;30m';      UBLA='\033[4;30m';      LBLA='\033[5;30m';      IBLA='\033[0;90m';      BIBLA='\033[1;90m';     On_BLA='\033[40m';      On_IBLA='\033[0;100m';
RED='\033[0;31m';       BRED='\033[1;31m';      URED='\033[4;31m';      LRED='\033[5;31m';      IRED='\033[0;91m';      BIRED='\033[1;91m';     On_RED='\033[41m';      On_IRED='\033[0;101m';
GRE='\033[0;32m';       BGRE='\033[1;32m';      UGRE='\033[4;32m';      LGRE='\033[5;32m';      IGRE='\033[0;92m';      BIGRE='\033[1;92m';     On_GRE='\033[42m';      On_IGRE='\033[0;102m';
YEL='\033[0;33m';       BYEL='\033[1;33m';      UYEL='\033[4;33m';      LYEL='\033[5;33m';      IYEL='\033[0;93m';      BIYEL='\033[1;93m';     On_YEL='\033[43m';      On_IYEL='\033[0;103m';
BLU='\033[0;34m';       BBLU='\033[1;34m';      UBLU='\033[4;34m';      LBLU='\033[5;34m';      IBLU='\033[0;94m';      BIBLU='\033[1;94m';     On_BLU='\033[44m';      On_IBLU='\033[0;104m';
PUR='\033[0;35m';       BPUR='\033[1;35m';      UPUR='\033[4;35m';      LPUR='\033[5;35m';      IPUR='\033[0;95m';      BIPUR='\033[1;95m';     On_PUR='\033[45m';      On_IPUR='\033[0;105m';
CYA='\033[0;36m';       BCYA='\033[1;36m';      UCYA='\033[4;36m';      LCYA='\033[5;36m';      ICYA='\033[0;96m';      BICYA='\033[1;96m';     On_CYA='\033[46m';      On_ICYA='\033[0;106m';
WHI='\033[0;37m';       BWHI='\033[1;37m';      UWHI='\033[4;37m';      LWHI='\033[5;37m';      IWHI='\033[0;97m';      BIWHI='\033[1;97m';     On_WHI='\033[47m';      On_IWHI='\033[0;107m';
}

if [[ -z "$RST" ]]; then
  set_colors
fi


